### PR TITLE
Feature/php7

### PR DESCRIPTION
**Pull request by chrootlogin**

### CODE REVIEW

**Comment by chrootlogin** [comment]
There is currently a bug in alpine PHP 7.0. Waiting for a new version of PHP7.

**Comment by chrootlogin** [comment]
@hulmgulm If you have a recent kernel on your docker host, feel free to use this feature branch with `docker run chrootlogin/nextcloud:dev-feature_php7`, but I will merge it to master after this bug is fixed. 
But on a recent kernel you won't have any problems.

**Comment by francislavoie** [comment]
It doesn't seem that this'll be backported to alpine 3.5, I think you should just use alpine edge with PHP 7.1 https://bugs.alpinelinux.org/issues/7277

The other option, use https://hub.docker.com/_/php/ as your base instead. That way, you can get a specific PHP version which is known as stable. I think this is a much better solution than relying on the apk repo

**Comment by chrootlogin** [comment]
You're right.

I created a new branch feature/php7_official_image (#14).

**Pull request closed without merging**
